name: cluster1
namespace: cluster1
controller: 1
worker: 1
subnet: 10.0.0.0/24
keypath: ~/.ssh/id_rsa.pub
memory: 20G
cpu: "8"
tag: latest
image: "containerdisk-ubuntu:20.04.1"
distro: ubuntu
suffix: local
kubeconfigdir: /tmp/cluster1
podv4subnet: 10.234.64.0/18
podv6subnet: fd85:ee78:d8a6:8607::2:0/112
servicev4subnet: 10.234.0.0/18
servicev6subnet: fd85:ee78:d8a6:8607::2000/116
asn: 64512
routes:
- 10.0.1.0/24
- 10.0.2.0/24
